pipeline {
    agent any

    tools {
        maven 'maven'
    }

    environment {
        DOCKER_IMAGE_BACKEND = 'thantuan/backend-app:latest'  // Tên image backend
        DOCKER_IMAGE_FRONTEND = 'thantuan/frontend-app:latest'  // Tên image frontend
    }

    stages {
        stage('Packaging/Pushing image') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/') {
                    sh 'docker build -t ${DOCKER_IMAGE_BACKEND} -f ./../backend/Dockerfile .'
                    sh 'docker build -t ${DOCKER_IMAGE_FRONTEND} -f ./../frontend/Dockerfile .'
                    sh 'docker push ${DOCKER_IMAGE_BACKEND}'
                    sh 'docker push ${DOCKER_IMAGE_FRONTEND}'
                }
            }
        }
        stage('Deploy to Production') {
            steps {
                sh 'ansible-playbook -i inventory.ini deploy.yml --limit production'
            }
        }
        stage('Deploy to Development') {
            steps {
                sh 'ansible-playbook -i inventory.ini deploy.yml --limit development'
            }
        }
    }
}