services:
  db:
    image: postgres:latest
    container_name: db-app
    env_file:
      - ./backend/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-java
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend-app
    env_file:
      - ./backend/.env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ecommerce-java
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend-app
    env_file:
      - ./frontend/.env.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ecommerce-java
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce-java
    restart: unless-stopped

networks:
  ecommerce-java:

volumes:
  pgdata:
