services:
  db:
    image: postgres:latest
    container_name: db-app
    env_file:
      - ./backend/.env.prod
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-java

  backend:
    image: thantuan/backend-app:latest
    pull_policy: always
    container_name: backend-app
    build:
      context: ./backend
      args:
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    env_file:
      - ./backend/.env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - ecommerce-java

  frontend:
    image: thantuan/frontend-app:latest
    pull_policy: always
    container_name: frontend-app
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - SERVER_API_URL=${SERVER_API_URL}
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    env_file:
      - ./frontend/.env.prod
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - ecommerce-java

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce-java

networks:
  ecommerce-java:
    name: ecommerce-java
    driver: bridge

volumes:
  pgdata:

