services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ~/.ssh:/root/.ssh
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - ecommerce-java

  ansible:
    image: alpine/ansible:latest
    container_name: ansible
    volumes:
      - /ansible:/ansible
      - ~/.ssh:/root/.ssh
    networks:
      - ecommerce-java

networks:
  ecommerce-java:
    name: ecommerce-java
    driver: bridge

volumes:
  jenkins_home:
  ansible_data: