- name: Deploy application using Docker Compose
  hosts: dev
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Stop existing containers
      docker_compose:
        project_src: D:/Learn/Web/ecommerce
        state: absent
    - name: Start new containers
      docker_compose:
        project_src: D:/Learn/Web/ecommerce
        file: D:/Learn/Web/ecommerce/docker-compose.dev.yml
        state: present