version: '3.9'

services:
  jenkins:
    build: .
    container_name: jenkins_ansible
    ports:
      - "8080:8080"
      - "50000:50000" # Port cho Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Kết nối Docker Host
      - /usr/bin/docker:/usr/bin/docker           # Docker CLI
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Bỏ qua thiết lập ban đầu
      - DOCKER_HOST=tcp://host.docker.internal:2375
    user: root # Chạy với quyền root để tránh lỗi truy cập socket Docker

volumes:
  jenkins_home:
