- name: Deploy application using Docker Compose
  hosts: prod
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Pull latest images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "{{ backend_image }}"
        - "{{ frontend_image }}"
    - name: Copy docker-compose file
      copy:
        src: D:/Learn/Web/ecommerce/docker-compose.prod.yml
        dest: /home/ubuntu/docker-compose.yml
    - name: Stop existing containers
      docker_compose:
        project_src: D:/Learn/Web/ecommerce
        state: absent
    - name: Start new containers
      docker_compose:
        project_src: D:/Learn/Web/ecommerce
        file: D:/Learn/Web/ecommerce/docker-compose.prod.yml
        state: present